name: inspireui
description: Common library inhouse inspireui company
version: 0.0.10
publish_to: "none"
author: inspireui
homepage: https://inspireui.com/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^4.1.0
  timeago: ^3.0.2
  pedantic: ^1.11.0
  intl: ^0.17.0
  event_bus: ^2.0.0
  encrypt: ^5.0.0
  dio: 4.0.0
  logger: ^1.0.0
  intro_slider: ^2.4.3
